concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# Name of the workflow
name: Node.js CI

# Specifies when the workflow should be triggered
on:
  # Triggers the workflow on 'push' events to the 'main' branch
  push:
    branches: [ main ]
  # Also triggers the workflow on 'pull_request' events targeting the 'main' branch
  pull_request:
    branches: [ main ]

# Defines the jobs that the workflow will execute
jobs:
  # Job identifier, can be any name (here it's 'build')
  build:
    # Specifies the type of virtual host environment (runner) to use
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Strategy for running the jobs - this section is useful for testing across multiple environments
    strategy:
      # A matrix build strategy to test against multiple versions of Node.js
      matrix:
        node-version: [14.x, 16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Sets up the specified version of Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Installs node modules as specified in the project's package-lock.json
      - name: Install Dependencies
        run: npm ci

      # This command will only run if a build script is defined in the package.json
      - name: Build Project (if applicable)
        run: npm run build --if-present
        continue-on-error: true  # Prevents auto-cancel

      # Runs tests as defined in the project's package.json
      - name: Run Tests
        run: npm test

